SELECT TOP (1000) [Id]
      ,[ApplicantName]
      ,[DateOfBirth]
      ,[PassportNumber]
      ,[Nationality]
      ,[ApplicationDate]
      ,[StatusId]
      ,[VisaTypeId]
  FROM [VisaAppDB].[dbo].[VisaApplication]